# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
- build
- deploy

build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - docker login registry.gitlab.com -u $DOCKER_USER -p $DOCKER_PASS
    - docker build -t $DOCKER_REGISTRY .
    - docker push $DOCKER_REGISTRY
  only:
    refs:
      - main
  when: manual
  allow_failure: false

deploy:
  image: ruby:2.5
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apk update && apk add openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
  script:
    - ssh -vvv -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "cd $REMOTE_PATH && docker pull $DOCKER_REGISTRY && exit"
    - ssh -vvv -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "cd $REMOTE_PATH && docker-compose up -d && exit"
  only:
    refs:
      - main
  needs: [build]
