import { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { TextInput, Text, Button, Flex } from '@mantine/core';
// import styles from '../styles/Home.module.css'

export default function Home() {

  const [nominal, setNominal] = useState<number>(0);
  const [bungaPertahun, setBungaPertahun] = useState<number>(0);
  const [lamaSimpan, setLamaSimpan] = useState<number>(0);
  const [akumulasi, setAkumulasi] = useState<number>(0);

  const hitung = () => {
    setAkumulasi(
      nominal * Math.pow(1 + (bungaPertahun / 100) / 12, 12 * lamaSimpan)
    );
  }

  return (
    <>
      <Head>
        <title>Compound Interest | Gugus Literasi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TextInput
          value={nominal}
          onChange={(e: React.FormEvent<HTMLInputElement>) => setNominal(parseFloat(e.currentTarget.value))}
          type="number"
          placeholder="1000"
          label="Modal Awal"
          rightSectionWidth={92}
          icon={'Rp.'}
        />
        <TextInput
          value={bungaPertahun}
          onChange={(e: React.ChangeEvent<HTMLInputElement>) => setBungaPertahun(parseFloat(e.target.value))}
          style={{ marginTop: 5 }}
          type="number"
          placeholder="Contoh: 5"
          label="Bunga"
          rightSectionWidth={120}
          rightSection={<Text c="dimmed">% per Tahun</Text>}
        />
        <TextInput
          value={lamaSimpan}
          onChange={(e: React.FormEvent<HTMLInputElement>) => setLamaSimpan(parseFloat(e.currentTarget.value))}
          style={{ marginTop: 5 }}
          type="number"
          placeholder="Contoh: 25"
          label="Jangka Waktu"
          rightSectionWidth={70}
          rightSection={<Text c="dimmed">Tahun</Text>}
        />
        <Flex
          style={{ marginTop: 15 }}
          gap="md"
          justify="space-between"
          align="flex-start"
          direction="row"
          wrap="wrap"
        >
          <Text fz="xl">Total: {akumulasi.toFixed(2)}</Text>
          <Button onClick={hitung}>
            Hitung
          </Button>
        </Flex>
      </main>
    </>
  )
}
