import { useState } from 'react';
import Head from 'next/head'
import { TextInput, Table, Text, Button, Flex } from '@mantine/core';

function comp(principal: number, interest: number, time: number) {
  const cent = interest / 100;
  return principal * Math.pow(1 + cent, time);
}

export default function Home() {

  const [nominal, setNominal] = useState<number>(0);
  const [bungaPertahun, setBungaPertahun] = useState<number>(0);
  const [lamaSimpan, setLamaSimpan] = useState<number>(0);
  const [akumulasi, setAkumulasi] = useState<number>(0);
  const [rows, setRows] = useState<any>();

  const hitung = () => {
    setAkumulasi(() => comp(nominal, bungaPertahun, lamaSimpan));

    setRows(() => Array.from(Array(lamaSimpan).keys())
    .map((i) => {
      const seq = i + 1;
      const acc = comp(nominal, bungaPertahun, seq);
      return (
        <tr key={i}>
          <td>{seq}</td>
          <td>{acc.toFixed(2)}</td>
          <td>{(acc - nominal).toFixed(2)}</td>
        </tr>
      )
    }))

  }

  return (
    <>
      <Head>
        <title>Compound Interest | Gugus Literasi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TextInput
          value={nominal}
          onChange={(e: React.FormEvent<HTMLInputElement>) => setNominal(parseFloat(e.currentTarget.value))}
          type="number"
          placeholder="1000"
          label="Modal Awal"
          rightSectionWidth={92}
          icon={'Rp.'}
        />
        <TextInput
          value={bungaPertahun}
          onChange={(e: React.ChangeEvent<HTMLInputElement>) => setBungaPertahun(parseFloat(e.target.value))}
          style={{ marginTop: 5 }}
          type="number"
          placeholder="Contoh: 5"
          label="Bunga"
          rightSectionWidth={120}
          rightSection={<Text c="dimmed">% per Tahun</Text>}
        />
        <TextInput
          value={lamaSimpan}
          onChange={(e: React.FormEvent<HTMLInputElement>) => setLamaSimpan(parseFloat(e.currentTarget.value))}
          style={{ marginTop: 5 }}
          type="number"
          placeholder="Contoh: 25"
          label="Jangka Waktu"
          rightSectionWidth={70}
          rightSection={<Text c="dimmed">Tahun</Text>}
        />
        <Flex
          style={{ marginTop: 15 }}
          gap="md"
          justify="space-between"
          align="flex-start"
          direction="row"
          wrap="wrap"
        >
          <Text fz="xl">Total: {akumulasi.toFixed(2)}</Text>
          <Button onClick={hitung}>
            Hitung
          </Button>
        </Flex>

        <Table>
          <thead>
            <tr>
              <th>#</th>
              <th>Akumulasi</th>
              <th>Bunga Bersih</th>
            </tr>
          </thead>
          <tbody>{rows}</tbody>
        </Table>
      </main>
    </>
  )
}
