import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { TextInput, Text } from '@mantine/core';
// import styles from '../styles/Home.module.css'

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TextInput
          type="number"
          placeholder="1000"
          label="Modal Awal"
          rightSectionWidth={92}
          icon={'Rp.'}
        />
        <TextInput
          style={{ marginTop: 5 }}
          type="number"
          placeholder="Contoh: 5"
          label="Bunga (% Per Tahun)"
          rightSectionWidth={120}
          rightSection={<Text c="dimmed">% per Tahun</Text>}
        />
        <TextInput
          style={{ marginTop: 5 }}
          type="number"
          placeholder="Contoh: 25"
          label="Jangka Waktu (Tahun)"
          rightSectionWidth={90}
          rightSection={<Text c="dimmed">Tahun</Text>}
        />
      </main>
    </>
  )
}
